<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Update Profile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>40e5c16f-d1f9-49be-8edd-1ec2edc4b0fa</testSuiteGuid>
   <testCaseLink>
      <guid>d3c53b61-5fc3-401e-9e59-665a8d5e4553</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Update Profile/TCPRO002 - User update their profile name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac357b39-b0d1-47f7-80a8-5db225342ffd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12dbd936-c6ff-4a9a-9f0e-1bad50486314</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Update Profile/TCPRO003 - User update their phone number</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5100a04a-cc13-436c-a383-c9bed58ccfa9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a55dbe8-b333-4ede-85c2-8f9fdef98dc9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Update Profile/TCPRO004 - User update their profile city</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>003a3323-a286-4138-9909-d35fcf447b2b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a16236d-38fd-4a9b-9b5d-885f8656c6c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Update Profile/TCPRO005 - User update their address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01053082-d4ec-49db-be53-8fa15699f8b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28579010-bc0d-43ce-96ad-9b031d3c7fb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Update Profile/TCPRO006 - User update their email address</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0276b484-4ebb-498d-8bfc-ab91331f9389</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>99891d7e-8442-4111-9eb2-a103d703100d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Update Profile/TCPRO007 - User update their password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e28c116b-7c01-4ee4-a3a0-e8f4b350cbbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e4de38a-2f4d-4960-85e1-9def66f03b91</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
