<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Add Product Test Suites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c7da9699-2945-4bb3-aeb8-4686ba40a085</testSuiteGuid>
   <testCaseLink>
      <guid>1984d135-0b9b-4bc6-913b-95af84dcee8b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd001 - Add Product Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1ea8aea-dcb2-4453-b6bb-917fec2eb1ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deefec4a-2abf-4f6b-b60b-6e93ca132454</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3a112cc-e554-4b10-8a1f-498d98b7ce46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f64f2de-b20a-41e1-ba0e-9dcbddcd0c8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f25dc428-fcfb-4db6-bc21-65f4126d1364</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd002 - Preview Product Before the Product Wants To Be Published</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3e5ca3c-f264-445f-b256-2c4c359bcdf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ccf591-bee6-4217-80fc-83ecf9d66b69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>623a17c5-5d37-4ee7-8831-62ef4a253e10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8aa93770-ece2-4953-a2f9-1016b4e7439a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea843b91-d51c-472c-9c5a-052de88231dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd003 - Add Product By Empty All the Forms Add Product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ace280cd-5265-4831-8e33-6196ea046bc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da63b835-51c2-4149-a207-019514c2e5ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c3ce0ee-69c7-45c8-b6e4-fa756494f11a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21075cd1-3e63-4973-b5c8-fc2a0fd13f4a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d5a3f62-591b-41b0-b230-de335aad5441</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd004 - Add Product Without Filling In the Nama Produk Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bda82d4-56ce-46c2-b330-8982ee27c767</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09cc4c06-6a0f-486a-aa51-991f8420788b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd1913a4-90a9-484c-b8bd-886beb76a5ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a753ebb-72c3-47f3-ab34-331b3b0a1046</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bea4c727-a001-468a-9d92-fec573572b09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd005 - Add Product Without Filling In the Harga Produk Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5901857a-dd5a-47be-b1af-be3638605e81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50c54c7c-1381-4736-9e77-762878517699</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49a2fc2e-c52b-4758-8c5a-65230b91ac68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0deb27c1-af84-432d-80cd-5c81cb1c2271</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>147a2869-42c7-4aca-add8-6e10963c1ca0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd006 - Add Product Without Select Kategori Produk Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>598f44cb-ba76-4def-84a0-6f3c843a133d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f57f0fc-4d2e-4fdf-82ed-155a0e13d1dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f185231a-2c8d-47cb-a351-7df092b50322</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19f6bef1-01a4-42be-9d30-f1907d29aa35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3b81b11-2ae6-4490-9a3d-5f6119a20367</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd007 - Add Product Without Filling In the Deskripsi Produk Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>592436b7-ce6a-4844-9568-24c4c1f4f56a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6087a924-2b24-49df-97e8-732891121238</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2c2a80-ce7c-4e86-b577-1cd4e6cd5968</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab159f3d-f6e3-47a2-aea7-f898809dfea4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cd0be4e-2b61-4341-8c83-317319587d99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd008 - Add Product Without Filling In the Add Image Product Form</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e38c27cc-204a-4a81-9955-1349e6bfc35b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82e6de4e-3f05-498e-a153-b32d22850e2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c87efb3-8c3e-4101-b8e2-51c3e381161a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10d69afc-b87d-4b5f-9b40-a359a4f2b78d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>822965b2-8d1a-4e94-b478-60a8493f1f37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd009 - Add Product With Image Product With A File Extension Other Than jpg</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>834d8e50-08cd-4bb4-bf92-95ca68040228</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7405ba96-a75b-4ec1-a5f8-7ed7f22c4434</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>308aea1d-9cba-4f6e-a886-2b33f4831caa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11b52b2a-9148-4e5b-bcb0-ee2142cbf6d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7541450c-e8b2-46fd-b939-c73d61701d45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Add Product/TCAdd010 - Add Product With Harga Produk Field Filling In With E Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6b0c36-e23c-434f-8d84-7b7bad2d21f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aae24946-a443-42bb-a6b3-c13eaa952fda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6768cfc-bb51-49d7-ac4f-9385fa62b2ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>982dbd1c-7acc-44e3-b212-f20185e2e932</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
