<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Edit Product Test Suites</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f829ab0f-0541-4f21-a707-3a2418075530</testSuiteGuid>
   <testCaseLink>
      <guid>98f22558-5ed8-4621-95ae-785d32e53478</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit001 - Edit Product Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77e4315-7d26-4570-addb-d388fb720275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa2dc3-5138-42ed-ac97-96f4b60dfef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf12e51e-5073-42ad-89b4-51c93de28c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e1dd26-3797-4bdb-895c-c357fa9f5ad8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a5094fb-9338-414b-a995-7baf17b5753b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit002 - Edit Product Without Does Not Change Data</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fa1cfdbe-d0d9-4871-bbba-31d10f587fb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit003 - Edit Product By Empty All the Forms Edit Product</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77e4315-7d26-4570-addb-d388fb720275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa2dc3-5138-42ed-ac97-96f4b60dfef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf12e51e-5073-42ad-89b4-51c93de28c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e1dd26-3797-4bdb-895c-c357fa9f5ad8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c15ed456-c735-4c79-8e3d-9dbf5bbfba15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit004 - Edit Product With Empty In the Nama Produk Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77e4315-7d26-4570-addb-d388fb720275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa2dc3-5138-42ed-ac97-96f4b60dfef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf12e51e-5073-42ad-89b4-51c93de28c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e1dd26-3797-4bdb-895c-c357fa9f5ad8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84ecd6a5-090d-485a-b0be-7af545bfd52a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit005 - Edit Product With Empty In the Harga Produk Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77e4315-7d26-4570-addb-d388fb720275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa2dc3-5138-42ed-ac97-96f4b60dfef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf12e51e-5073-42ad-89b4-51c93de28c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e1dd26-3797-4bdb-895c-c357fa9f5ad8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>780c57d4-baef-413e-834a-575301e161c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit006 - Edit Product With Empty In the Deskripsi Produk Field</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77e4315-7d26-4570-addb-d388fb720275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa2dc3-5138-42ed-ac97-96f4b60dfef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf12e51e-5073-42ad-89b4-51c93de28c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e1dd26-3797-4bdb-895c-c357fa9f5ad8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3348f69-c7e2-48cf-af20-fa5393ebca4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit007 - Edit Product With Change Image Product With A File Extension Other Than jpg</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77e4315-7d26-4570-addb-d388fb720275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa2dc3-5138-42ed-ac97-96f4b60dfef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf12e51e-5073-42ad-89b4-51c93de28c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e1dd26-3797-4bdb-895c-c357fa9f5ad8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d0e79d2-a1bb-4cc5-8d08-10fcc40c0f96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Edit Product/TCEdit008 - Edit Product With Harga Produk Field Filling In With E Alphabet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77e4315-7d26-4570-addb-d388fb720275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fa2dc3-5138-42ed-ac97-96f4b60dfef9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf12e51e-5073-42ad-89b4-51c93de28c3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40e1dd26-3797-4bdb-895c-c357fa9f5ad8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
